name: bharat_intelligence_mobile
description: A Flutter mobile app for Bharat Intelligence admin operations
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Mobile-optimized UI Components
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Utilities
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.5.1
  
  # Navigation
  go_router: ^14.6.1
  
  # Mobile-specific
  device_info_plus: ^11.1.0
  connectivity_plus: ^6.1.0
  package_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env